# Generated by Django 5.0.3 on 2024-09-06 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=120)),
                ('event_desc', models.TextField(blank=True, max_length=300, null=True)),
                ('event_start', models.DateTimeField()),
                ('event_end', models.DateTimeField()),
                ('event_venue', models.TextField(max_length=120)),
                ('event_status', models.TextField(choices=[('In Progress', 'in progress'), ('Canceled', 'canceled'), ('Scheduled', 'scheduled'), ('Closed', 'closed'), ('On-Hold', 'on-hold'), ('Completed', 'completed'), ('Stopped', 'stopped')], max_length=50)),
                ('isCompleted', models.BooleanField(default=False)),
                ('event_img', models.ImageField(blank=True, null=True, upload_to='event_img/')),
                ('event_thumb', models.ImageField(blank=True, editable=False, null=True, upload_to='event_thumb/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('event_slug', models.SlugField(editable=False, unique=True)),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.organizer')),
            ],
        ),
    ]
