# Generated by Django 5.0.3 on 2024-09-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_event_organizer_delete_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_start',
            field=models.DateField(),
        ),
    ]
