# Generated by Django 5.0.3 on 2024-09-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_organizer_alter_event_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
