# Generated by Django 5.1.1 on 2024-09-23 09:28

import django.contrib.auth.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0006_ticket_date_purchased_ticket_ticket_event_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendee',
            options={},
        ),
        migrations.AlterModelManagers(
            name='attendee',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='password',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='username',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='email',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('In Progress', 'in progress'), ('Canceled', 'canceled'), ('Scheduled', 'scheduled'), ('Closed', 'closed'), ('On-Hold', 'on-hold'), ('Completed', 'completed'), ('Stopped', 'stopped')], max_length=50),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(max_length=300, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='core_user_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='core_user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='attendee',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attendee', to='core.user'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to='core.user'),
        ),
    ]
