# Generated by Django 5.1.1 on 2024-09-23 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_attendee_options_alter_attendee_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='isCompleted',
            new_name='is_completed',
        ),
        migrations.AlterField(
            model_name='attendee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendee', to='core.user'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.event'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.attendee'),
        ),
    ]
