# Generated by Django 5.1.1 on 2024-10-19 04:20

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_iscompleted_event_is_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_created',
            field=core.models.CustomDateTimeField(auto_now_add=True),
        ),
    ]
