# Generated by Django 5.1.1 on 2024-10-19 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_event_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, choices=[('Lagos', 'lagos'), ('Abuja', 'Abuja'), ('Abijan', 'Abijan'), ('Cotè d` ivore', 'Cotè d` ivore'), ('Capetown', 'Capetown'), ('Johanesburg', 'Johanesburg'), ('Accra, Ghana', 'Accra Ghana')], max_length=80, null=True),
        ),
    ]
