# Generated by Django 5.1.1 on 2024-10-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, choices=[('Lagos, Nigeria', 'lagos, Nigeria'), ('Calabar, Nigeria', 'Calabar, Nigeria'), ('Abuja, Nigeria', 'Abuja, Nigeria'), ('Abidjan, Cotè d` ivore', 'Abidjan, Cotè d` ivore'), ('Cotè d` ivore', 'Cotè d` ivore'), ('Capetown, SA', 'Capetown, SA'), ('Johanesburg, SA', 'Johanesburg, SA'), ('Accra, Ghana', 'Accra, Ghana')], max_length=80, null=True),
        ),
    ]
