# Generated by Django 5.1.1 on 2024-10-25 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.user'),
        ),
    ]
