# Generated by Django 5.1.1 on 2024-10-27 14:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_ticket_ticket_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='event_img'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_thumb',
            field=cloudinary.models.CloudinaryField(blank=True, editable=False, max_length=255, null=True, verbose_name='event_thumb'),
        ),
    ]
