# Generated by Django 5.1.1 on 2024-10-27 14:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_event_event_img_alter_event_event_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_thumb',
            field=cloudinary.models.CloudinaryField(blank=True, editable=False, max_length=255, null=True, verbose_name='image'),
        ),
    ]
