# Generated by Django 5.1.1 on 2024-10-10 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarApp', '0002_rename_event_eventtracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtracking',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
