# Generated by Django 5.1.1 on 2024-10-24 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarApp', '0003_eventtracking_reminder_sent'),
        ('core', '0011_alter_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtracking',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.event'),
        ),
    ]
